pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/manaspratimdas/patient-record-ms.git'
				
            }
        }
        
                stage('Build') {
            steps {
                script {
                    dir('PatientRecordMS') {
                        bat 'mvn clean'
                    }
                }
            }
        }
      
        
    }
}